project:
  type: website
  output-dir: docs

website:
  title: "Portfolio Asesmen II-2100 KIPP"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: All_About_me/index.qmd
        text: UTS-1
      - href: My_Song_for_You/index.qmd
        text: UTS-2
      - href: My_Stories_for_You/index.qmd
        text: UTS-3
      - href: My_Shapes/index.qmd
        text: UTS-4
      - href: My_Personal_Reviews/index.qmd
        text: UTS-5
      - href: My_Concepts/index.qmd
        text: UAS-1
      - href: My_Opinions/index.qmd
        text: UAS-2
      - href: My_Innovations/index.qmd
        text: UAS-3
      - href: My_Knowledge/index.qmd
        text: UAS-4
      - href: My_Professional_Reviews/index.qmd
        text: UAS-5

  page-footer:
    left: "© 2025 Riantama Putra – 18224061 – Sistem dan Teknologi Informasi ITB"

format:
  html:
    theme: cosmo
    toc: true