project:
  type: website
  output-dir: docs

website:
  title: "Riantama Putra"
  subtitle: "Portfolio Asesmen II-2100 KIPP"
  author: "18224061 Riantama Putra"
  date: "10/22/2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: All_About_me/index.qmd
        text: UTS-1
      - href: My_Song_for_You/index.qmd
        text: UTS-2
      - href: My_Stories_for_You/index.qmd
        text: UTS-3
      - href: My_Shapes/index.qmd
        text: UTS-4
      - href: My_Personal_Reviews/index.qmd
        text: UTS-5

format:
  html:
    theme: cosmo
    toc: true
